### ISSUE TITLE
A request for help - Breaking Cuffs (police)

### ISSUE THREAD

**Issue by iplocator** [NathanERP/qb-lock#7]
Hi, Thank you for your time in advance.

I'm attempting to use this script to enable players to "break cuffs" when arrested by police. I am unable to figure out how I can trigger the minigame to the player being cuffed and not the player cuffing. **<--- (Hope that makes sense)**

Here is how I have set the function at the moment...

```
RegisterNetEvent('police:client:MinigameCuffPlayer', function()
    if not IsPedRagdoll(PlayerPedId()) then
        local player, distance = QBCore.Functions.GetClosestPlayer()
        if player ~= -1 and distance < 1.5 then
            QBCore.Functions.TriggerCallback('QBCore:HasItem', function(result)
                if result then 
                    local playerId = GetPlayerServerId(player)
                    if not IsPedInAnyVehicle(GetPlayerPed(player)) and not IsPedInAnyVehicle(PlayerPedId()) then
                    local seconds = math.random(4,6)
                    local circles = 1
                    local success = exports['qb-lock']:StartLockPickCircle(circles, seconds, success)
                    if success then
                        TriggerClientEvent('QBCore:Notify', playerId.PlayerData.source, "You broke cuffs!")
                    else
                        TriggerServerEvent("police:server:CuffPlayer", playerId, false)
                        HandCuffAnimation()
                        TriggerClientEvent('QBCore:Notify', playerId.PlayerData.source, "You have been cuffed!")
                    end
                    else
                        QBCore.Functions.Notify("You can\'t cuff someone in a vehicle", "error")
                    end
                else
                    QBCore.Functions.Notify("You don\'t have handcuffs on you", "error")
                end
            end, "handcuffs")
        else
            QBCore.Functions.Notify("No one nearby!", "error")
        end
    else
        Wait(2000)
    end
end)
```

Shot in the dark and I have no idea how to contact you NathanERP, but any help would be greatly appreciated!

Kind Regards IPL

**Comment by NathanERP** [comment]
RegisterNetEvent('police:client:GetCuffed')
AddEventHandler('police:client:GetCuffed', function(playerId, isSoftcuff)
    if not isHandcuffed then
        local seconds = math.random(3,6)
        local success = exports['qb-lock']:StartLockPickCircle(1, seconds, success)
        print(success)
        if not success then
            isHandcuffed = true
            TriggerServerEvent("police:server:SetHandcuffStatus", true)
            ClearPedTasksImmediately(PlayerPedId())
            if GetSelectedPedWeapon(PlayerPedId()) ~= GetHashKey('WEAPON_UNARMED') then
                SetCurrentPedWeapon(PlayerPedId(), GetHashKey('WEAPON_UNARMED'), true)
            end
            if not isSoftcuff then
                cuffType = 16
                GetCuffedAnimation(playerId)
                QBCore.Functions.Notify("You are cuffed!")
            else
                cuffType = 49
                GetCuffedAnimation(playerId)
                QBCore.Functions.Notify("You are cuffed, but you can walk")
            end
        else
            QBCore.Functions.Notify("You managed to break free", "success")
        end
    else
        isHandcuffed = false
        isEscorted = false
        TriggerEvent('hospital:client:isEscorted', isEscorted)
        DetachEntity(PlayerPedId(), true, false)
        TriggerServerEvent("police:server:SetHandcuffStatus", false)
        ClearPedTasksImmediately(PlayerPedId())
        QBCore.Functions.Notify("You are uncuffed!")
    end
end)

**Comment by NathanERP** [comment]
`
RegisterNetEvent('police:client:GetCuffed')
AddEventHandler('police:client:GetCuffed', function(playerId, isSoftcuff)
    if not isHandcuffed then
        local seconds = math.random(3,6)
        local success = exports['qb-lock']:StartLockPickCircle(1, seconds, success)
        print(success)
        if not success then
            isHandcuffed = true
            TriggerServerEvent("police:server:SetHandcuffStatus", true)
            ClearPedTasksImmediately(PlayerPedId())
            if GetSelectedPedWeapon(PlayerPedId()) ~= GetHashKey('WEAPON_UNARMED') then
                SetCurrentPedWeapon(PlayerPedId(), GetHashKey('WEAPON_UNARMED'), true)
            end
            if not isSoftcuff then
                cuffType = 16
                GetCuffedAnimation(playerId)
                QBCore.Functions.Notify("You are cuffed!")
            else
                cuffType = 49
                GetCuffedAnimation(playerId)
                QBCore.Functions.Notify("You are cuffed, but you can walk")
            end
        else
            QBCore.Functions.Notify("You managed to break free", "success")
        end
    else
        isHandcuffed = false
        isEscorted = false
        TriggerEvent('hospital:client:isEscorted', isEscorted)
        DetachEntity(PlayerPedId(), true, false)
        TriggerServerEvent("police:server:SetHandcuffStatus", false)
        ClearPedTasksImmediately(PlayerPedId())
        QBCore.Functions.Notify("You are uncuffed!")
    end
end)
`

**Comment by Nathan-FiveM** [comment]
```lua
RegisterNetEvent('police:client:GetCuffed', function(playerId, isSoftcuff)
    if not isHandcuffed then
        local seconds = math.random(3,6)
        local success = exports['qb-lock']:StartLockPickCircle(1, seconds, success)
        print(success)
        if not success then
            isHandcuffed = true
            TriggerServerEvent("police:server:SetHandcuffStatus", true)
            ClearPedTasksImmediately(PlayerPedId())
            if GetSelectedPedWeapon(PlayerPedId()) ~= GetHashKey('WEAPON_UNARMED') then
                SetCurrentPedWeapon(PlayerPedId(), GetHashKey('WEAPON_UNARMED'), true)
            end
            if not isSoftcuff then
                cuffType = 16
                GetCuffedAnimation(playerId)
                QBCore.Functions.Notify("You are cuffed!")
            else
                cuffType = 49
                GetCuffedAnimation(playerId)
                QBCore.Functions.Notify("You are cuffed, but you can walk")
            end
        else
            QBCore.Functions.Notify("You managed to break free", "success")
        end
    else
        isHandcuffed = false
        isEscorted = false
        TriggerEvent('hospital:client:isEscorted', isEscorted)
        DetachEntity(PlayerPedId(), true, false)
        TriggerServerEvent("police:server:SetHandcuffStatus", false)
        ClearPedTasksImmediately(PlayerPedId())
        QBCore.Functions.Notify("You are uncuffed!")
    end
end)
```
Replace the event "police:client:GetCuffed" with the one above

**Comment by iplocator** [comment]
NathanERP, You're an absolute legend!

Thank You Very Much! Beautiful Code ;)

**Comment by njstrong** [comment]
How do I make it less circles and faster?

**Comment by scruuffyy** [comment]
anyway to make the circle faster i set it to the lowest and its still super slow

**Comment by njstrong** [comment]
I ended up using a snippet that calls event from  qb skillbar and it worked
much better. Got it from qb core framework discord
